
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kubra
 */
public class RadioButtonComboBox extends javax.swing.JFrame {

    /**
     * Creates new form RadioButtonComboBox
     */
    public RadioButtonComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Set<String> diller=new LinkedHashSet<String>();
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnJava = new javax.swing.JRadioButton();
        btnPhp = new javax.swing.JRadioButton();
        btnPyhton = new javax.swing.JRadioButton();
        btnGoster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(btnJava);
        btnJava.setText("Java");

        buttonGroup1.add(btnPhp);
        btnPhp.setText("PHP");
        btnPhp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhpActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnPyhton);
        btnPyhton.setText("Pyhton");
        btnPyhton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPyhtonActionPerformed(evt);
            }
        });

        btnGoster.setText("Göster");
        btnGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPyhton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGoster)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPhp)
                                .addComponent(btnJava)))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnJava)
                .addGap(18, 18, 18)
                .addComponent(btnPhp)
                .addGap(18, 18, 18)
                .addComponent(btnPyhton)
                .addGap(18, 18, 18)
                .addComponent(btnGoster)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnPhpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPhpActionPerformed

    private void btnPyhtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyhtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPyhtonActionPerformed

    public void goster(){
        String mesaj="";
        if(diller.isEmpty()){
            mesaj+="Seçilen dil yok";
        }
        else{
            mesaj+="Seçilen diller:";
            for(String dil:diller){
                mesaj+=dil+" ";
            }
        }
        JOptionPane.showMessageDialog(this, mesaj);
             
    }
    private void btnGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGosterActionPerformed
        // TODO add your handling code here:
        if(btnJava.isSelected()){
            diller.add("Java");
        }
        else{
            diller.remove("Java");
        }
        if(btnPhp.isSelected()){
            diller.add("PHP");
        }
        else{
            diller.remove("PHP");
        }
        if(btnPyhton.isSelected()){
            diller.add("Pyhton");
        }
        else{
            diller.remove("Pyhton");
        }
        goster();
        
    }//GEN-LAST:event_btnGosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButtonComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButtonComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButtonComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButtonComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButtonComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoster;
    private javax.swing.JRadioButton btnJava;
    private javax.swing.JRadioButton btnPhp;
    private javax.swing.JRadioButton btnPyhton;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
