
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kubra
 */
public class SiparisUygulamasi extends javax.swing.JFrame {

    /**
     * Creates new form SiparisUygulamasi
     */
    public SiparisUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chxIskender = new javax.swing.JCheckBox();
        chxCorba = new javax.swing.JCheckBox();
        chxKunefe = new javax.swing.JCheckBox();
        chxSalad = new javax.swing.JCheckBox();
        chxAyran = new javax.swing.JCheckBox();
        btnSiparis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sipariş Uygulaması");

        chxIskender.setText("İskender-20 tl");

        chxCorba.setText("Çorba-8 tl");

        chxKunefe.setText("Künefe-10 tl");

        chxSalad.setText("Salata 6 tl");

        chxAyran.setText("Ayran-2 tl");

        btnSiparis.setText("Sipariş Ver");
        btnSiparis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiparisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSiparis)
                    .addComponent(chxAyran)
                    .addComponent(chxSalad)
                    .addComponent(chxKunefe)
                    .addComponent(chxCorba)
                    .addComponent(chxIskender))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(chxIskender)
                .addGap(18, 18, 18)
                .addComponent(chxCorba)
                .addGap(18, 18, 18)
                .addComponent(chxKunefe)
                .addGap(18, 18, 18)
                .addComponent(chxSalad)
                .addGap(18, 18, 18)
                .addComponent(chxAyran)
                .addGap(18, 18, 18)
                .addComponent(btnSiparis)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Map<String,Integer> siparisler=new LinkedHashMap<String, Integer>();
    public void siparisleriGoster(){
        String message="";
        int tutar=0;
        if(siparisler.isEmpty()){
            message+="Siparişiniz bulunmamaktadır.";
        }
        else{
            for(Map.Entry<String,Integer> entry:siparisler.entrySet()){
                
                tutar+=entry.getValue();
                message+=entry.getKey()+"\n";        
            }
            message+="Tutar: "+tutar;
        }
        JOptionPane.showMessageDialog(this, message);
    }
    
    private void btnSiparisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiparisActionPerformed
        // TODO add your handling code here:
        String siparis="";
        int tutar=0;
        if(chxIskender.isSelected()){
           siparisler.put("Iskender", 20);
        }
        else{
            siparisler.remove("Iskender");
        }
          if(chxAyran.isSelected()){
           siparisler.put("Ayran", 2);
        }
        else{
            siparisler.remove("Ayran");
        }
        if(chxCorba.isSelected()){
           siparisler.put("Corba", 8);
        }
        else{
            siparisler.remove("Corba");
        }
        if(chxKunefe.isSelected()){
           siparisler.put("Kunefe", 10);
        }
        else{
            siparisler.remove("Kunefe");
        }
        if(chxSalad.isSelected()){
           siparisler.put("Salata", 6);
        }
        else{
            siparisler.remove("Salata");
        }
        siparisleriGoster();
    }//GEN-LAST:event_btnSiparisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiparis;
    private javax.swing.JCheckBox chxAyran;
    private javax.swing.JCheckBox chxCorba;
    private javax.swing.JCheckBox chxIskender;
    private javax.swing.JCheckBox chxKunefe;
    private javax.swing.JCheckBox chxSalad;
    // End of variables declaration//GEN-END:variables
}
