/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swinguygulama2;

/**
 *
 * @author Kubra
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnToplama = new javax.swing.JButton();
        btnCikarma = new javax.swing.JButton();
        btnBolme = new javax.swing.JButton();
        btnCarpma = new javax.swing.JButton();
        lblBirinci = new javax.swing.JLabel();
        lblIkinci = new javax.swing.JLabel();
        lblSonuc = new javax.swing.JLabel();
        txtBirinci = new javax.swing.JTextField();
        txtIkıncı = new javax.swing.JTextField();
        txtSonuc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnToplama.setText("Toplama");
        btnToplama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplamaActionPerformed(evt);
            }
        });

        btnCikarma.setText("Çıkarma");
        btnCikarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikarmaActionPerformed(evt);
            }
        });

        btnBolme.setText("Bölme");
        btnBolme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolmeActionPerformed(evt);
            }
        });

        btnCarpma.setText("Çarpma");
        btnCarpma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpmaActionPerformed(evt);
            }
        });

        lblBirinci.setText("Birinci Sayı:");

        lblIkinci.setText("İkinci Sayı:");

        lblSonuc.setText("Sonuç:");

        txtSonuc.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnToplama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBolme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCikarma)
                            .addComponent(btnCarpma)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBirinci)
                            .addComponent(lblIkinci)
                            .addComponent(lblSonuc))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSonuc, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(txtIkıncı)
                            .addComponent(txtBirinci))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBirinci)
                    .addComponent(txtBirinci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIkinci)
                    .addComponent(txtIkıncı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSonuc)
                    .addComponent(txtSonuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToplama)
                    .addComponent(btnCikarma))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBolme)
                    .addComponent(btnCarpma))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToplamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplamaActionPerformed
        // TODO add your handling code here:
        int birinciSayi=Integer.valueOf(txtBirinci.getText());
        int ikinciSayi=Integer.valueOf(txtIkıncı.getText());
        int sonuc=birinciSayi+ikinciSayi;
        txtSonuc.setText(String.valueOf(sonuc));
        
    }//GEN-LAST:event_btnToplamaActionPerformed

    private void btnCikarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikarmaActionPerformed
        // TODO add your handling code here:
        int birinciSayi=Integer.valueOf(txtBirinci.getText());
        int ikinciSayi=Integer.valueOf(txtIkıncı.getText());
        int sonuc=birinciSayi-ikinciSayi;
        txtSonuc.setText(String.valueOf(sonuc));
        
    }//GEN-LAST:event_btnCikarmaActionPerformed

    private void btnBolmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolmeActionPerformed
        // TODO add your handling code here:
        int birinciSayi=Integer.valueOf(txtBirinci.getText());
        int ikinciSayi=Integer.valueOf(txtIkıncı.getText());
        //double sonuc=(double)birinciSayi/ikinciSayi;
        txtSonuc.setText(String.valueOf((double)birinciSayi/ikinciSayi));
        
    }//GEN-LAST:event_btnBolmeActionPerformed

    private void btnCarpmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpmaActionPerformed
        // TODO add your handling code here:
        int birinciSayi=Integer.valueOf(txtBirinci.getText());
        int ikinciSayi=Integer.valueOf(txtIkıncı.getText());
        int sonuc=birinciSayi*ikinciSayi;
        txtSonuc.setText(String.valueOf(sonuc));
        
    }//GEN-LAST:event_btnCarpmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBolme;
    private javax.swing.JButton btnCarpma;
    private javax.swing.JButton btnCikarma;
    private javax.swing.JButton btnToplama;
    private javax.swing.JLabel lblBirinci;
    private javax.swing.JLabel lblIkinci;
    private javax.swing.JLabel lblSonuc;
    private javax.swing.JTextField txtBirinci;
    private javax.swing.JTextField txtIkıncı;
    private javax.swing.JTextField txtSonuc;
    // End of variables declaration//GEN-END:variables
}
